// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyC_YOUR_WEB_API_KEY',
//     appId: '1:525472168794:web:YOUR_WEB_APP_ID',
//     messagingSenderId: '525472168794',
//     projectId: 'vigilant-design-464014-k4',
//     authDomain: 'vigilant-design-464014-k4.firebaseapp.com',
//     storageBucket: 'vigilant-design-464014-k4.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBnkpirK3QLu6UCEqjmU5sv3_Jq1azwVVM',
//     appId: '1:626038617447:android:031aa8c7bc8973ecd82bc2',
//     messagingSenderId: '626038617447',
//     projectId: 'archminton-e0926',
//     storageBucket: 'archminton-e0926.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDUNbEsqqaO1BzjvU0tM51L3IkhDSsGERU',
//     appId: '1:626038617447:ios:6b2ad8d11556440cd82bc2',
//     messagingSenderId: '626038617447',
//     projectId: 'archminton-e0926',
//     storageBucket: 'archminton-e0926.firebasestorage.app',
//     iosClientId: '626038617447-q92k02v6qoqejentf7o95kpsv97qrto9.apps.googleusercontent.com',
//     iosBundleId: 'com.archminton.app',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyC_YOUR_MACOS_API_KEY',
//     appId: '1:525472168794:macos:c7e4e3e8b8f9a1b2c3d4e5f6',
//     messagingSenderId: '525472168794',
//     projectId: 'vigilant-design-464014-k4',
//     storageBucket: 'vigilant-design-464014-k4.appspot.com',
//     iosBundleId: 'com.archminton.app',
//   );
// } 